// flow-typed signature: 5a7ab2c059ccfcc24a744425bf6009e8
// flow-typed version: <<STUB>>/aws-amplify_v3.3.26/flow_v0.148.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'aws-amplify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'aws-amplify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'aws-amplify/build' {
  declare module.exports: any;
}

declare module 'aws-amplify/dist/aws-amplify' {
  declare module.exports: any;
}

declare module 'aws-amplify/dist/aws-amplify.min' {
  declare module.exports: any;
}

declare module 'aws-amplify/lib-esm/Common/types/types' {
  declare module.exports: any;
}

declare module 'aws-amplify/lib-esm' {
  declare module.exports: any;
}

declare module 'aws-amplify/lib-esm/withSSRContext' {
  declare module.exports: any;
}

declare module 'aws-amplify/lib/Common/types/types' {
  declare module.exports: any;
}

declare module 'aws-amplify/lib' {
  declare module.exports: any;
}

declare module 'aws-amplify/lib/withSSRContext' {
  declare module.exports: any;
}

declare module 'aws-amplify/webpack-utils' {
  declare module.exports: any;
}

declare module 'aws-amplify/webpack.config.dev' {
  declare module.exports: any;
}

// Filename aliases
declare module 'aws-amplify/build.js' {
  declare module.exports: $Exports<'aws-amplify/build'>;
}
declare module 'aws-amplify/dist/aws-amplify.js' {
  declare module.exports: $Exports<'aws-amplify/dist/aws-amplify'>;
}
declare module 'aws-amplify/dist/aws-amplify.min.js' {
  declare module.exports: $Exports<'aws-amplify/dist/aws-amplify.min'>;
}
declare module 'aws-amplify/index' {
  declare module.exports: $Exports<'aws-amplify'>;
}
declare module 'aws-amplify/index.js' {
  declare module.exports: $Exports<'aws-amplify'>;
}
declare module 'aws-amplify/lib-esm/Common/types/types.js' {
  declare module.exports: $Exports<'aws-amplify/lib-esm/Common/types/types'>;
}
declare module 'aws-amplify/lib-esm/index' {
  declare module.exports: $Exports<'aws-amplify/lib-esm'>;
}
declare module 'aws-amplify/lib-esm/index.js' {
  declare module.exports: $Exports<'aws-amplify/lib-esm'>;
}
declare module 'aws-amplify/lib-esm/withSSRContext.js' {
  declare module.exports: $Exports<'aws-amplify/lib-esm/withSSRContext'>;
}
declare module 'aws-amplify/lib/Common/types/types.js' {
  declare module.exports: $Exports<'aws-amplify/lib/Common/types/types'>;
}
declare module 'aws-amplify/lib/index' {
  declare module.exports: $Exports<'aws-amplify/lib'>;
}
declare module 'aws-amplify/lib/index.js' {
  declare module.exports: $Exports<'aws-amplify/lib'>;
}
declare module 'aws-amplify/lib/withSSRContext.js' {
  declare module.exports: $Exports<'aws-amplify/lib/withSSRContext'>;
}
declare module 'aws-amplify/webpack-utils.js' {
  declare module.exports: $Exports<'aws-amplify/webpack-utils'>;
}
declare module 'aws-amplify/webpack.config.dev.js' {
  declare module.exports: $Exports<'aws-amplify/webpack.config.dev'>;
}
