// flow-typed signature: 4f7076b404d18e4c3e7b748fbd832677
// flow-typed version: <<STUB>>/graphviz-react_v1.1.1/flow_v0.139.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'graphviz-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'graphviz-react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
//declare module 'graphviz-react/lib/Graphviz' {
//  declare module.exports: any;
//}

// Filename aliases
//declare module 'graphviz-react/lib/Graphviz.js' {
//  declare module.exports: $Exports<'graphviz-react/lib/Graphviz'>;
//}
