// flow-typed signature: 5eabcf10c3813337c295d073098c683b
// flow-typed version: <<STUB>>/@aws-amplify/ui-react_v1.0.6/flow_v0.148.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@aws-amplify/ui-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@aws-amplify/ui-react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@aws-amplify/ui-react/build' {
  declare module.exports: any;
}

declare module '@aws-amplify/ui-react/dist/@aws-amplify/ui-react' {
  declare module.exports: any;
}

declare module '@aws-amplify/ui-react/dist/0' {
  declare module.exports: any;
}

declare module '@aws-amplify/ui-react/dist/1' {
  declare module.exports: any;
}

declare module '@aws-amplify/ui-react/dist/10' {
  declare module.exports: any;
}

declare module '@aws-amplify/ui-react/dist/11' {
  declare module.exports: any;
}

declare module '@aws-amplify/ui-react/dist/12' {
  declare module.exports: any;
}

declare module '@aws-amplify/ui-react/dist/13' {
  declare module.exports: any;
}

declare module '@aws-amplify/ui-react/dist/14' {
  declare module.exports: any;
}

declare module '@aws-amplify/ui-react/dist/15' {
  declare module.exports: any;
}

declare module '@aws-amplify/ui-react/dist/16' {
  declare module.exports: any;
}

declare module '@aws-amplify/ui-react/dist/17' {
  declare module.exports: any;
}

declare module '@aws-amplify/ui-react/dist/18' {
  declare module.exports: any;
}

declare module '@aws-amplify/ui-react/dist/19' {
  declare module.exports: any;
}

declare module '@aws-amplify/ui-react/dist/2' {
  declare module.exports: any;
}

declare module '@aws-amplify/ui-react/dist/20' {
  declare module.exports: any;
}

declare module '@aws-amplify/ui-react/dist/21' {
  declare module.exports: any;
}

declare module '@aws-amplify/ui-react/dist/22' {
  declare module.exports: any;
}

declare module '@aws-amplify/ui-react/dist/23' {
  declare module.exports: any;
}

declare module '@aws-amplify/ui-react/dist/24' {
  declare module.exports: any;
}

declare module '@aws-amplify/ui-react/dist/25' {
  declare module.exports: any;
}

declare module '@aws-amplify/ui-react/dist/26' {
  declare module.exports: any;
}

declare module '@aws-amplify/ui-react/dist/27' {
  declare module.exports: any;
}

declare module '@aws-amplify/ui-react/dist/28' {
  declare module.exports: any;
}

declare module '@aws-amplify/ui-react/dist/29' {
  declare module.exports: any;
}

declare module '@aws-amplify/ui-react/dist/3' {
  declare module.exports: any;
}

declare module '@aws-amplify/ui-react/dist/30' {
  declare module.exports: any;
}

declare module '@aws-amplify/ui-react/dist/31' {
  declare module.exports: any;
}

declare module '@aws-amplify/ui-react/dist/32' {
  declare module.exports: any;
}

declare module '@aws-amplify/ui-react/dist/33' {
  declare module.exports: any;
}

declare module '@aws-amplify/ui-react/dist/4' {
  declare module.exports: any;
}

declare module '@aws-amplify/ui-react/dist/5' {
  declare module.exports: any;
}

declare module '@aws-amplify/ui-react/dist/6' {
  declare module.exports: any;
}

declare module '@aws-amplify/ui-react/dist/7' {
  declare module.exports: any;
}

declare module '@aws-amplify/ui-react/dist/8' {
  declare module.exports: any;
}

declare module '@aws-amplify/ui-react/dist/9' {
  declare module.exports: any;
}

declare module '@aws-amplify/ui-react/dist/aws-amplify-react.min' {
  declare module.exports: any;
}

declare module '@aws-amplify/ui-react/dist/polyfills-core-js' {
  declare module.exports: any;
}

declare module '@aws-amplify/ui-react/dist/polyfills-css-shim' {
  declare module.exports: any;
}

declare module '@aws-amplify/ui-react/dist/polyfills-dom' {
  declare module.exports: any;
}

declare module '@aws-amplify/ui-react/jest.config' {
  declare module.exports: any;
}

declare module '@aws-amplify/ui-react/lib-esm/components' {
  declare module.exports: any;
}

declare module '@aws-amplify/ui-react/lib-esm' {
  declare module.exports: any;
}

declare module '@aws-amplify/ui-react/lib-esm/react-component-lib/createComponent' {
  declare module.exports: any;
}

declare module '@aws-amplify/ui-react/lib-esm/react-component-lib/createControllerComponent' {
  declare module.exports: any;
}

declare module '@aws-amplify/ui-react/lib-esm/react-component-lib/createOverlayComponent' {
  declare module.exports: any;
}

declare module '@aws-amplify/ui-react/lib-esm/react-component-lib' {
  declare module.exports: any;
}

declare module '@aws-amplify/ui-react/lib-esm/react-component-lib/utils/attachEventProps' {
  declare module.exports: any;
}

declare module '@aws-amplify/ui-react/lib-esm/react-component-lib/utils' {
  declare module.exports: any;
}

declare module '@aws-amplify/ui-react/lib-esm/withAuthenticator' {
  declare module.exports: any;
}

declare module '@aws-amplify/ui-react/lib/components' {
  declare module.exports: any;
}

declare module '@aws-amplify/ui-react/lib' {
  declare module.exports: any;
}

declare module '@aws-amplify/ui-react/lib/react-component-lib/createComponent' {
  declare module.exports: any;
}

declare module '@aws-amplify/ui-react/lib/react-component-lib/createControllerComponent' {
  declare module.exports: any;
}

declare module '@aws-amplify/ui-react/lib/react-component-lib/createOverlayComponent' {
  declare module.exports: any;
}

declare module '@aws-amplify/ui-react/lib/react-component-lib' {
  declare module.exports: any;
}

declare module '@aws-amplify/ui-react/lib/react-component-lib/utils/attachEventProps' {
  declare module.exports: any;
}

declare module '@aws-amplify/ui-react/lib/react-component-lib/utils' {
  declare module.exports: any;
}

declare module '@aws-amplify/ui-react/lib/withAuthenticator' {
  declare module.exports: any;
}

declare module '@aws-amplify/ui-react/webpack.config.dev' {
  declare module.exports: any;
}

declare module '@aws-amplify/ui-react/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module '@aws-amplify/ui-react/build.js' {
  declare module.exports: $Exports<'@aws-amplify/ui-react/build'>;
}
declare module '@aws-amplify/ui-react/dist/@aws-amplify/ui-react.js' {
  declare module.exports: $Exports<'@aws-amplify/ui-react/dist/@aws-amplify/ui-react'>;
}
declare module '@aws-amplify/ui-react/dist/0.js' {
  declare module.exports: $Exports<'@aws-amplify/ui-react/dist/0'>;
}
declare module '@aws-amplify/ui-react/dist/1.js' {
  declare module.exports: $Exports<'@aws-amplify/ui-react/dist/1'>;
}
declare module '@aws-amplify/ui-react/dist/10.js' {
  declare module.exports: $Exports<'@aws-amplify/ui-react/dist/10'>;
}
declare module '@aws-amplify/ui-react/dist/11.js' {
  declare module.exports: $Exports<'@aws-amplify/ui-react/dist/11'>;
}
declare module '@aws-amplify/ui-react/dist/12.js' {
  declare module.exports: $Exports<'@aws-amplify/ui-react/dist/12'>;
}
declare module '@aws-amplify/ui-react/dist/13.js' {
  declare module.exports: $Exports<'@aws-amplify/ui-react/dist/13'>;
}
declare module '@aws-amplify/ui-react/dist/14.js' {
  declare module.exports: $Exports<'@aws-amplify/ui-react/dist/14'>;
}
declare module '@aws-amplify/ui-react/dist/15.js' {
  declare module.exports: $Exports<'@aws-amplify/ui-react/dist/15'>;
}
declare module '@aws-amplify/ui-react/dist/16.js' {
  declare module.exports: $Exports<'@aws-amplify/ui-react/dist/16'>;
}
declare module '@aws-amplify/ui-react/dist/17.js' {
  declare module.exports: $Exports<'@aws-amplify/ui-react/dist/17'>;
}
declare module '@aws-amplify/ui-react/dist/18.js' {
  declare module.exports: $Exports<'@aws-amplify/ui-react/dist/18'>;
}
declare module '@aws-amplify/ui-react/dist/19.js' {
  declare module.exports: $Exports<'@aws-amplify/ui-react/dist/19'>;
}
declare module '@aws-amplify/ui-react/dist/2.js' {
  declare module.exports: $Exports<'@aws-amplify/ui-react/dist/2'>;
}
declare module '@aws-amplify/ui-react/dist/20.js' {
  declare module.exports: $Exports<'@aws-amplify/ui-react/dist/20'>;
}
declare module '@aws-amplify/ui-react/dist/21.js' {
  declare module.exports: $Exports<'@aws-amplify/ui-react/dist/21'>;
}
declare module '@aws-amplify/ui-react/dist/22.js' {
  declare module.exports: $Exports<'@aws-amplify/ui-react/dist/22'>;
}
declare module '@aws-amplify/ui-react/dist/23.js' {
  declare module.exports: $Exports<'@aws-amplify/ui-react/dist/23'>;
}
declare module '@aws-amplify/ui-react/dist/24.js' {
  declare module.exports: $Exports<'@aws-amplify/ui-react/dist/24'>;
}
declare module '@aws-amplify/ui-react/dist/25.js' {
  declare module.exports: $Exports<'@aws-amplify/ui-react/dist/25'>;
}
declare module '@aws-amplify/ui-react/dist/26.js' {
  declare module.exports: $Exports<'@aws-amplify/ui-react/dist/26'>;
}
declare module '@aws-amplify/ui-react/dist/27.js' {
  declare module.exports: $Exports<'@aws-amplify/ui-react/dist/27'>;
}
declare module '@aws-amplify/ui-react/dist/28.js' {
  declare module.exports: $Exports<'@aws-amplify/ui-react/dist/28'>;
}
declare module '@aws-amplify/ui-react/dist/29.js' {
  declare module.exports: $Exports<'@aws-amplify/ui-react/dist/29'>;
}
declare module '@aws-amplify/ui-react/dist/3.js' {
  declare module.exports: $Exports<'@aws-amplify/ui-react/dist/3'>;
}
declare module '@aws-amplify/ui-react/dist/30.js' {
  declare module.exports: $Exports<'@aws-amplify/ui-react/dist/30'>;
}
declare module '@aws-amplify/ui-react/dist/31.js' {
  declare module.exports: $Exports<'@aws-amplify/ui-react/dist/31'>;
}
declare module '@aws-amplify/ui-react/dist/32.js' {
  declare module.exports: $Exports<'@aws-amplify/ui-react/dist/32'>;
}
declare module '@aws-amplify/ui-react/dist/33.js' {
  declare module.exports: $Exports<'@aws-amplify/ui-react/dist/33'>;
}
declare module '@aws-amplify/ui-react/dist/4.js' {
  declare module.exports: $Exports<'@aws-amplify/ui-react/dist/4'>;
}
declare module '@aws-amplify/ui-react/dist/5.js' {
  declare module.exports: $Exports<'@aws-amplify/ui-react/dist/5'>;
}
declare module '@aws-amplify/ui-react/dist/6.js' {
  declare module.exports: $Exports<'@aws-amplify/ui-react/dist/6'>;
}
declare module '@aws-amplify/ui-react/dist/7.js' {
  declare module.exports: $Exports<'@aws-amplify/ui-react/dist/7'>;
}
declare module '@aws-amplify/ui-react/dist/8.js' {
  declare module.exports: $Exports<'@aws-amplify/ui-react/dist/8'>;
}
declare module '@aws-amplify/ui-react/dist/9.js' {
  declare module.exports: $Exports<'@aws-amplify/ui-react/dist/9'>;
}
declare module '@aws-amplify/ui-react/dist/aws-amplify-react.min.js' {
  declare module.exports: $Exports<'@aws-amplify/ui-react/dist/aws-amplify-react.min'>;
}
declare module '@aws-amplify/ui-react/dist/polyfills-core-js.js' {
  declare module.exports: $Exports<'@aws-amplify/ui-react/dist/polyfills-core-js'>;
}
declare module '@aws-amplify/ui-react/dist/polyfills-css-shim.js' {
  declare module.exports: $Exports<'@aws-amplify/ui-react/dist/polyfills-css-shim'>;
}
declare module '@aws-amplify/ui-react/dist/polyfills-dom.js' {
  declare module.exports: $Exports<'@aws-amplify/ui-react/dist/polyfills-dom'>;
}
declare module '@aws-amplify/ui-react/jest.config.js' {
  declare module.exports: $Exports<'@aws-amplify/ui-react/jest.config'>;
}
declare module '@aws-amplify/ui-react/lib-esm/components.js' {
  declare module.exports: $Exports<'@aws-amplify/ui-react/lib-esm/components'>;
}
declare module '@aws-amplify/ui-react/lib-esm/index' {
  declare module.exports: $Exports<'@aws-amplify/ui-react/lib-esm'>;
}
declare module '@aws-amplify/ui-react/lib-esm/index.js' {
  declare module.exports: $Exports<'@aws-amplify/ui-react/lib-esm'>;
}
declare module '@aws-amplify/ui-react/lib-esm/react-component-lib/createComponent.js' {
  declare module.exports: $Exports<'@aws-amplify/ui-react/lib-esm/react-component-lib/createComponent'>;
}
declare module '@aws-amplify/ui-react/lib-esm/react-component-lib/createControllerComponent.js' {
  declare module.exports: $Exports<'@aws-amplify/ui-react/lib-esm/react-component-lib/createControllerComponent'>;
}
declare module '@aws-amplify/ui-react/lib-esm/react-component-lib/createOverlayComponent.js' {
  declare module.exports: $Exports<'@aws-amplify/ui-react/lib-esm/react-component-lib/createOverlayComponent'>;
}
declare module '@aws-amplify/ui-react/lib-esm/react-component-lib/index' {
  declare module.exports: $Exports<'@aws-amplify/ui-react/lib-esm/react-component-lib'>;
}
declare module '@aws-amplify/ui-react/lib-esm/react-component-lib/index.js' {
  declare module.exports: $Exports<'@aws-amplify/ui-react/lib-esm/react-component-lib'>;
}
declare module '@aws-amplify/ui-react/lib-esm/react-component-lib/utils/attachEventProps.js' {
  declare module.exports: $Exports<'@aws-amplify/ui-react/lib-esm/react-component-lib/utils/attachEventProps'>;
}
declare module '@aws-amplify/ui-react/lib-esm/react-component-lib/utils/index' {
  declare module.exports: $Exports<'@aws-amplify/ui-react/lib-esm/react-component-lib/utils'>;
}
declare module '@aws-amplify/ui-react/lib-esm/react-component-lib/utils/index.js' {
  declare module.exports: $Exports<'@aws-amplify/ui-react/lib-esm/react-component-lib/utils'>;
}
declare module '@aws-amplify/ui-react/lib-esm/withAuthenticator.js' {
  declare module.exports: $Exports<'@aws-amplify/ui-react/lib-esm/withAuthenticator'>;
}
declare module '@aws-amplify/ui-react/lib/components.js' {
  declare module.exports: $Exports<'@aws-amplify/ui-react/lib/components'>;
}
declare module '@aws-amplify/ui-react/lib/index' {
  declare module.exports: $Exports<'@aws-amplify/ui-react/lib'>;
}
declare module '@aws-amplify/ui-react/lib/index.js' {
  declare module.exports: $Exports<'@aws-amplify/ui-react/lib'>;
}
declare module '@aws-amplify/ui-react/lib/react-component-lib/createComponent.js' {
  declare module.exports: $Exports<'@aws-amplify/ui-react/lib/react-component-lib/createComponent'>;
}
declare module '@aws-amplify/ui-react/lib/react-component-lib/createControllerComponent.js' {
  declare module.exports: $Exports<'@aws-amplify/ui-react/lib/react-component-lib/createControllerComponent'>;
}
declare module '@aws-amplify/ui-react/lib/react-component-lib/createOverlayComponent.js' {
  declare module.exports: $Exports<'@aws-amplify/ui-react/lib/react-component-lib/createOverlayComponent'>;
}
declare module '@aws-amplify/ui-react/lib/react-component-lib/index' {
  declare module.exports: $Exports<'@aws-amplify/ui-react/lib/react-component-lib'>;
}
declare module '@aws-amplify/ui-react/lib/react-component-lib/index.js' {
  declare module.exports: $Exports<'@aws-amplify/ui-react/lib/react-component-lib'>;
}
declare module '@aws-amplify/ui-react/lib/react-component-lib/utils/attachEventProps.js' {
  declare module.exports: $Exports<'@aws-amplify/ui-react/lib/react-component-lib/utils/attachEventProps'>;
}
declare module '@aws-amplify/ui-react/lib/react-component-lib/utils/index' {
  declare module.exports: $Exports<'@aws-amplify/ui-react/lib/react-component-lib/utils'>;
}
declare module '@aws-amplify/ui-react/lib/react-component-lib/utils/index.js' {
  declare module.exports: $Exports<'@aws-amplify/ui-react/lib/react-component-lib/utils'>;
}
declare module '@aws-amplify/ui-react/lib/withAuthenticator.js' {
  declare module.exports: $Exports<'@aws-amplify/ui-react/lib/withAuthenticator'>;
}
declare module '@aws-amplify/ui-react/webpack.config.dev.js' {
  declare module.exports: $Exports<'@aws-amplify/ui-react/webpack.config.dev'>;
}
declare module '@aws-amplify/ui-react/webpack.config.js' {
  declare module.exports: $Exports<'@aws-amplify/ui-react/webpack.config'>;
}
