# Build Specification Reference for CodeBuild: https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html

version: 0.2

phases:
  install:
    runtime-versions:
      ruby: latest
  build:
    commands:
      - curl -o /tmp/net-task.tar.gz -L https://github.com/rwilcox/net-task/releases/download/0.1.0/net-task_0.1.0_Linux_x86_64.tar.gz
      - cd /tmp/; tar -xvzf net-task.tar.gz; cd -
      - bash build-scripts/pre-build.sh
      - bash build-scripts/test.sh
      - bash build-scripts/package.sh

artifacts:
  files:
    - '**/*'
  base-directory: 'modules/frontend/build'
# TODO: use secondary artifacts
